
import { NgxUiLoaderConfig, POSITION, SPINNER, PB_DIRECTION } from 'ngx-ui-loader';
export const ngxUiLoaderConfig: NgxUiLoaderConfig = {
    "bgsColor": "#b5e4dc",
    "bgsOpacity": 0.4,
    "bgsPosition": "bottom-right",
    "bgsSize": 60,
    "bgsType": "ball-spin-clockwise",
    "blur": 2,
    "delay": 0,
    "fastFadeOut": true,
    "fgsColor": "#b5e4dc",
    "fgsPosition": "center-center",
    "fgsSize": 100,
    "fgsType": "three-strings",
    "gap": 29,
    "logoPosition": "top-center",
    "logoSize": 120,
    "logoUrl": "",
    "masterLoaderId": "master",
    "overlayBorderRadius": "0",
    "overlayColor": "rgba(40,40,40,0.5)",
    "pbColor": "red",
    "pbDirection": "ltr",
    "pbThickness": 3,
    "hasProgressBar": true,
    "text": "GORYSTY TRAVELERS",
    "textColor": "#b5e4dc",
    "textPosition": "center-center",
    "maxTime": -1,
    "minTime": 300
};
